[package]
name = "micrograd_rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Main"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
uuid = {version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"]}