[package]
name = "micrograd_rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Value"
path = "src/value.rs"

[dependencies]
uuid = {version = "1.10.0", features = ["v4", "fast-rng", "macro-diagnostics"]}